name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy the contents of the demo folder to GitHub Pages under the "jsonresume" folder.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGE_TOKEN }}
          publish_dir: ./demo
          destination_dir: jsonresume
