name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # adjust as needed

      # 3. Install dependencies.
      - name: Install dependencies
        run: npm ci

      # 4. Copy the published npm package into the demo folder.
      - name: Copy npm package into demo folder
        run: |
          # Create the necessary folder structure inside demo
          mkdir -p demo/node_modules/@kyzrfranz
          # Copy the package folder into demo/node_modules
          cp -R node_modules/@kyzrfranz/jsonresume-terminal demo/node_modules/@kyzrfranz/
          # (Optional) Log what was copied for debugging
          ls -la demo/node_modules/@kyzrfranz

      # 5. Deploy the contents of the demo folder to the gh-pages branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGE_TOKEN }}  # your PAT secret with repo access
          publish_dir: ./demo
